-- ============================================================
-- NOVAS TABELAS - Paz Church WhatsApp Bot
-- Execute este SQL no painel do Supabase (SQL Editor)
-- ============================================================

-- Tabela de Pedidos de Oração
CREATE TABLE IF NOT EXISTS prayer_requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone       TEXT NOT NULL,
    member_name TEXT,
    request     TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    answered    BOOLEAN DEFAULT FALSE  -- Pastor pode marcar como respondido depois
);

-- Index para busca por data
CREATE INDEX IF NOT EXISTS idx_prayer_requests_created ON prayer_requests(created_at DESC);

-- Tabela de Presença/Check-in
CREATE TABLE IF NOT EXISTS attendance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         TEXT NOT NULL,
    member_name   TEXT,
    checked_in_at TIMESTAMPTZ DEFAULT NOW(),
    day_of_week   INT,   -- 0=Dom, 1=Seg, ..., 6=Sáb
    event_name    TEXT DEFAULT 'Culto Dominical'
);

-- Index para relatórios por data
CREATE INDEX IF NOT EXISTS idx_attendance_checked ON attendance(checked_in_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_phone   ON attendance(phone);

-- ============================================================
-- PERMISSÕES (Row Level Security)
-- Se o projeto usa RLS, adicione as políticas abaixo.
-- ============================================================

-- Desabilitar RLS nestas tabelas (mais simples para o bot):
ALTER TABLE prayer_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance      DISABLE ROW LEVEL SECURITY;

-- OU habilitar e permitir tudo pela service_role:
-- ALTER TABLE prayer_requests ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "allow_all" ON prayer_requests FOR ALL USING (true);
