-- ================================================================
-- TABELAS - Paz Church Mondubim
-- Execute este SQL no painel do Supabase > SQL Editor
-- Mesmas tabelas da Paraipaba, mas com sufixo _mondubim
-- ================================================================


-- ----------------------------------------------------------------
-- 1. MEMBROS (members_mondubim)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS members_mondubim (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    phone         TEXT NOT NULL,                       -- ID do WhatsApp (usado internamente)
    phone_contact TEXT,                                -- Número legível formatado
    email         TEXT,
    cep           TEXT,
    address       TEXT,
    neighborhood  TEXT,
    birth_date    DATE,
    life_group    TEXT,                                -- Nome da célula/Life Group
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para busca rápida
CREATE INDEX IF NOT EXISTS idx_members_mondubim_phone      ON members_mondubim(phone);
CREATE INDEX IF NOT EXISTS idx_members_mondubim_name       ON members_mondubim(name);
CREATE INDEX IF NOT EXISTS idx_members_mondubim_life_group ON members_mondubim(life_group);
CREATE INDEX IF NOT EXISTS idx_members_mondubim_created    ON members_mondubim(created_at DESC);


-- ----------------------------------------------------------------
-- 2. PEDIDOS DE ORAÇÃO (prayer_requests_mondubim)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prayer_requests_mondubim (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone       TEXT NOT NULL,
    member_name TEXT,
    request     TEXT NOT NULL,
    answered    BOOLEAN DEFAULT FALSE,                 -- Pastor pode marcar como respondido
    answered_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prayer_mondubim_created  ON prayer_requests_mondubim(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prayer_mondubim_phone    ON prayer_requests_mondubim(phone);
CREATE INDEX IF NOT EXISTS idx_prayer_mondubim_answered ON prayer_requests_mondubim(answered);


-- ----------------------------------------------------------------
-- 3. PRESENÇA / CHECK-IN (attendance_mondubim)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance_mondubim (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         TEXT NOT NULL,
    member_name   TEXT,
    checked_in_at TIMESTAMPTZ DEFAULT NOW(),
    day_of_week   INT,                                 -- 0=Dom, 1=Seg, ..., 6=Sáb
    event_name    TEXT DEFAULT 'Culto Dominical'
);

CREATE INDEX IF NOT EXISTS idx_attendance_mondubim_checked ON attendance_mondubim(checked_in_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_mondubim_phone   ON attendance_mondubim(phone);


-- ----------------------------------------------------------------
-- 4. CELLS / LIFE GROUPS (lives_mondubim)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lives_mondubim (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,                        -- Nome do Life Group
    leader_name  TEXT,
    leader_phone TEXT,
    address      TEXT,
    neighborhood TEXT,
    meeting_day  TEXT,                                 -- Ex: "Terça-feira às 19h"
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION,
    active       BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lives_mondubim_active ON lives_mondubim(active);


-- ----------------------------------------------------------------
-- 5. BROADCASTS AGENDADOS (broadcasts_mondubim)
--    Tabela opcional para persistir disparos agendados
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS broadcasts_mondubim (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message        TEXT NOT NULL,
    image_url      TEXT,
    scheduled_at   TIMESTAMPTZ NOT NULL,
    sent           BOOLEAN DEFAULT FALSE,
    sent_at        TIMESTAMPTZ,
    recipients_cnt INT DEFAULT 0,
    created_by     TEXT DEFAULT 'admin',
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_broadcasts_mondubim_scheduled ON broadcasts_mondubim(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_broadcasts_mondubim_sent      ON broadcasts_mondubim(sent);


-- ----------------------------------------------------------------
-- 6. PERMISSÕES: desabilitar RLS para acesso via service_role
-- ----------------------------------------------------------------
ALTER TABLE members_mondubim          DISABLE ROW LEVEL SECURITY;
ALTER TABLE prayer_requests_mondubim  DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_mondubim       DISABLE ROW LEVEL SECURITY;
ALTER TABLE lives_mondubim            DISABLE ROW LEVEL SECURITY;
ALTER TABLE broadcasts_mondubim       DISABLE ROW LEVEL SECURITY;


-- ================================================================
-- DADOS INICIAIS: Life Groups de Exemplo (edite conforme necessário)
-- ================================================================
INSERT INTO lives_mondubim (name, leader_name, leader_phone, address, neighborhood, meeting_day, latitude, longitude)
VALUES
    ('Life Mondubim Centro',    'Líder A',  '85999990001', 'Rua Exemplo, 100',     'Mondubim',         'Terça-feira às 19h30', -3.8041, -38.5874),
    ('Life Granja Lisboa',      'Líder B',  '85999990002', 'Rua dos Lírios, 50',   'Granja Lisboa',    'Quinta-feira às 19h30',-3.8120, -38.5700),
    ('Life Conjunto Ceará',     'Líder C',  '85999990003', 'Av. Principal, 200',   'Conjunto Ceará',   'Quarta-feira às 19h',  -3.7950, -38.5950)
ON CONFLICT DO NOTHING;


-- ================================================================
-- VERIFICAÇÃO FINAL
-- ================================================================
SELECT
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns c WHERE c.table_name = t.table_name AND c.table_schema = 'public') AS num_colunas
FROM information_schema.tables t
WHERE table_schema = 'public'
  AND table_name LIKE '%_mondubim'
ORDER BY table_name;
